#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Make sure the following commands are always run in the same directory as the
# script, because some paths are relative or dependent on the current working
# directory.
pushd $SCRIPT_DIR

docker build -t package -f Dockerfile.package docker-context

docker run --rm -v $(pwd):/package/source -v $(pwd)/pkg-build:/package/build package build-package

popd
