#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker build -t package -f Dockerfile.package "$SCRIPT_DIR/docker-context"

docker run --rm -v "$SCRIPT_DIR:/package/source" -v "$SCRIPT_DIR/pkg-build:/package/build" package build-package
