node ('git') {
    stage ('checkout') {
        checkout scm
    }

    stage ('build') {
        // Report status of stage 'build' back to Gitlab
        gitlabCommitStatus(name: 'build') {
            def buildDir = 'harvesting/pkg-build'

            // Clean the build directory before starting
            sh "rm -rf ${buildDir}"
            sh "mkdir -p ${buildDir}"

            dir ('harvesting/debian') {
                sh './make-changelog'
            }

            sh './harvesting/package'

            publishPackages buildDir.toString(), 'common/stable', 'xenial'

            archiveArtifacts(artifacts: "${buildDir}/*")
        }
    }
}
